-- Auchan - prog6 Sinistres mensuels par periode_facture_prest
-- À la demande de Julien Vignal en date du 2019-05-21
-- Développé par Elie Busson le 2019-05-21

SET @deb = '2014-06-02', @fin = '2019-04-30';

SELECT T0.MOIS,
SUM(CASE WHEN T1.ANNEE = 2019 THEN T1.SINIS_FACT ELSE NULL END) AS '2019',
SUM(CASE WHEN T1.ANNEE = 2018 THEN T1.SINIS_FACT ELSE NULL END) AS '2018',
SUM(CASE WHEN T1.ANNEE = 2017 THEN T1.SINIS_FACT ELSE NULL END) AS '2017',
SUM(CASE WHEN T1.ANNEE = 2016 THEN T1.SINIS_FACT ELSE NULL END) AS '2016',
SUM(CASE WHEN T1.ANNEE = 2015 THEN T1.SINIS_FACT ELSE NULL END) AS '2015',
SUM(CASE WHEN T1.ANNEE = 2014 THEN T1.SINIS_FACT ELSE NULL END) AS '2014'
FROM
(
-- calendrier
SELECT DISTINCT EXTRACT(YEAR_MONTH FROM cal_date) AS ANNEE_MOIS,
EXTRACT(YEAR FROM cal_date) AS ANNEE,
EXTRACT(MONTH FROM cal_date) AS MOIS
FROM calendrier
WHERE cal_date BETWEEN @deb AND @fin
ORDER BY ANNEE_MOIS DESC
) T0
LEFT JOIN
(
-- periode prestation
SELECT EXTRACT(YEAR_MONTH FROM periode_facture_prest) AS ANNEE_MOIS,
EXTRACT(YEAR FROM periode_facture_prest) AS ANNEE,
EXTRACT(MONTH FROM periode_facture_prest) AS MOIS,
COUNT(DISTINCT CASE WHEN type_prestation <> 'EXPERTISE' THEN prestations_v1.ticket_id ELSE NULL END) AS SINIS_FACT, SUM(prix_ttc) AS FACTU_TTC_PRESTA
FROM prestations_v1
WHERE prestations_v1.id_programme = 6  AND prix_ttc<>0 AND periode_facture_prest BETWEEN @deb AND @fin
GROUP BY ANNEE_MOIS
ORDER BY ANNEE_MOIS DESC
) T1 ON T0.ANNEE_MOIS = T1.ANNEE_MOIS
GROUP BY T0.MOIS
WITH ROLLUP

